name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
    - name: install-deps
      run: sudo apt install libyaml-cpp-dev libatasmart-dev cmake
    - name: cmake
      run: |
        mkdir build
        cmake -B build
    - name: check version
      run: |
        git diff -- VERSION
        if [[ -n $(git diff -- VERSION) ]]; then
          echo "Error: VERSION file not in sync:"
          git diff -- VERSION
          exit 1
        fi
    - name: compile
      run: cmake --build build
    - name: install
      run: sudo cmake --install ${{ github.workspace }}/build
