name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/install_thinkfan_deps
    - uses: ./.github/actions/build_thinkfan
    - uses: ./.github/actions/install_thinkfan
